CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "TB_USER" (
    "UserId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "FictionalName" Varchar NOT NULL,
    "Email" Varchar NOT NULL,
    "PasswordHash" Varchar NOT NULL,
    "CellPhone" Varchar NOT NULL,
    "BirthDate" Varchar NOT NULL,
    "Uf" Varchar NOT NULL,
    "City" Varchar NOT NULL,
    "Role" text NOT NULL,
    "UserStatus" text NOT NULL,
    CONSTRAINT "PK_TB_USER" PRIMARY KEY ("UserId")
);

CREATE TABLE "TB_PUBLICATION" (
    "PublicationId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "PublicationContent" Varchar NOT NULL,
    "PublicationsRole" text NOT NULL,
    "PublicationStatus" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ModificationDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TB_PUBLICATION" PRIMARY KEY ("PublicationId"),
    CONSTRAINT "FK_TB_PUBLICATION_TB_USER_UserId" FOREIGN KEY ("UserId") REFERENCES "TB_USER" ("UserId")
);

CREATE TABLE "TB_ATTENDANCES" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "VolunteerId" bigint NOT NULL,
    "PublicationId" bigint NOT NULL,
    "StartedAt" timestamp with time zone NOT NULL,
    "IsCompleted" boolean NOT NULL,
    CONSTRAINT "PK_TB_ATTENDANCES" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TB_ATTENDANCES_TB_PUBLICATION_PublicationId" FOREIGN KEY ("PublicationId") REFERENCES "TB_PUBLICATION" ("PublicationId") ON DELETE CASCADE,
    CONSTRAINT "FK_TB_ATTENDANCES_TB_USER_VolunteerId" FOREIGN KEY ("VolunteerId") REFERENCES "TB_USER" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "TB_CHAT" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AttendanceId" bigint NOT NULL,
    CONSTRAINT "PK_TB_CHAT" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TB_CHAT_TB_ATTENDANCES_AttendanceId" FOREIGN KEY ("AttendanceId") REFERENCES "TB_ATTENDANCES" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TB_MESSAGES" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ChatId" bigint NOT NULL,
    "SenderId" bigint NOT NULL,
    "Content" Varchar NOT NULL,
    "SentAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_TB_MESSAGES" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TB_MESSAGES_TB_CHAT_ChatId" FOREIGN KEY ("ChatId") REFERENCES "TB_CHAT" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TB_MESSAGES_TB_USER_SenderId" FOREIGN KEY ("SenderId") REFERENCES "TB_USER" ("UserId") ON DELETE CASCADE
);

CREATE INDEX "IX_TB_ATTENDANCES_PublicationId" ON "TB_ATTENDANCES" ("PublicationId");

CREATE INDEX "IX_TB_ATTENDANCES_VolunteerId" ON "TB_ATTENDANCES" ("VolunteerId");

CREATE INDEX "IX_TB_CHAT_AttendanceId" ON "TB_CHAT" ("AttendanceId");

CREATE INDEX "IX_TB_MESSAGES_ChatId" ON "TB_MESSAGES" ("ChatId");

CREATE INDEX "IX_TB_MESSAGES_SenderId" ON "TB_MESSAGES" ("SenderId");

CREATE INDEX "IX_TB_PUBLICATION_UserId" ON "TB_PUBLICATION" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241104003454_InitialCreate', '8.0.10');

COMMIT;

